name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: ${{ secrets.TOMBOY }}
          TIMEZONE: Asia/Seoul
